<a href="https://colab.research.google.com/github/ArturBondarenko2004/-Artificial-intelligence-systems/blob/main/LR_1_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

2.1.1. Бінарізація

In [2]:
input_data = np.array([
    [-1.3, 3.9, 4.5],
    [-5.3, -4.2, -1.3],
    [5.2, -6.5, -1.1],
    [-5.2, 2.6, -2.2]
])

# Бінаризація даних
data_binarized = preprocessing.Binarizer(threshold=3).transform(input_data)
print("\n Binarized data:\n", data_binarized)


 Binarized data:
 [[0. 1. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]


2.1.2. Виключення середнього

In [3]:
# Виведення середнього значення та стандартного відхилення
print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# Виключення середнього
data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


BEFORE: 
Mean = [-1.65  -1.05  -0.025]
Std deviation = [4.27112397 4.40028408 2.64516068]

AFTER: 
Mean = [-2.77555756e-17  5.55111512e-17  5.55111512e-17]
Std deviation = [1. 1. 1.]


2.1.3. Масштабування

In [4]:
# Масштабування MinМax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nМin max scaled data:\n", data_scaled_minmax)



Мin max scaled data:
 [[0.38095238 1.         1.        ]
 [0.         0.22115385 0.13432836]
 [1.         0.         0.1641791 ]
 [0.00952381 0.875      0.        ]]


2.1.4. Нормалізація

In [5]:
# Нормалізація даних
data_normalized_l1 = preprocessing.normalize(input_data,
norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,
norm='l2')
print("\nl1 normalized data:\n", data_normalized_l1)
print("\nl2 normalized data:\n", data_normalized_l2)


l1 normalized data:
 [[-0.13402062  0.40206186  0.46391753]
 [-0.49074074 -0.38888889 -0.12037037]
 [ 0.40625    -0.5078125  -0.0859375 ]
 [-0.52        0.26       -0.22      ]]

l2 normalized data:
 [[-0.21328678  0.63986035  0.7383004 ]
 [-0.76965323 -0.60991388 -0.18878287]
 [ 0.61931099 -0.77413873 -0.13100809]
 [-0.83653629  0.41826814 -0.3539192 ]]
